name: agenda_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  animate_do: ^2.1.0
  cloud_firestore: ^3.1.13
  firebase_core: ^1.15.0
  provider: ^6.0.2
  
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true